{
 "title": "nzbget",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nzbget_standby", "legendFormat": "Standby" }
   ]
  },
  {
   "title": "Active Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(nzbget_news_server_active)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Time",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nzbget_history_par_time_seconds",
     "legendFormat": "Par"
    },
    {
     "expr": "nzbget_history_unpack_time_seconds",
     "legendFormat": "Unpack"
    },
    {
     "expr": "nzbget_history_par_repair_time_seconds",
     "legendFormat": "Par Repair"
    },
    {
     "expr": "nzbget_history_post_process_time_seconds",
     "legendFormat": "Post-Process"
    },
    {
     "expr": "nzbget_history_download_time_seconds",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "title": "Categories",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nzbget_history_category_count{category != \"\"}) by (category)",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Downloaded",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nzbget_downloaded_total_bytes\n",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Download Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nzbget_downloaded_total_bytes[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "nzbget DL Speed by Provider",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(server) (irate(nzbget_news_server_total_bytes[5m]))",
     "legendFormat": "{{server}}"
    },
    {
     "expr": "sum(irate(nzbget_news_server_total_bytes[5m]))\n",
     "legendFormat": "Total Throughput"
    }
   ]
  },
  {
   "title": "nzbget Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 18 },
   "targets": [
    { "expr": "sum(nzbget_thread_count)", "legendFormat": "Active Connections" }
   ]
  },
  {
   "title": "Download Per Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(nzbget_news_server_total_bytes) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  { "title": "Caches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Article Cache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(service) (nzbget_article_cache_bytes)",
     "legendFormat": "Article Cache"
    }
   ]
  },
  {
   "title": "Article Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(irate(nzbget_history_article_success_count[$__rate_interval]))",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "sum(irate(nzbget_history_article_failed_count[$__rate_interval]))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Article Success Rate",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 13, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nzbget_history_article_failed_count",
     "legendFormat": "Failed"
    },
    {
     "expr": "nzbget_history_article_success_count",
     "legendFormat": "Succeeded"
    }
   ]
  }
 ]
}